# Site wide configuration

titel: CompChemRano
locale: en_US
logo: # filename of a logo image that has been placed into your images directory
description: "Hello, my name is Jerrano Bowleg and I am Posdoctoral Fellow at [Research Triangle Institute International](https://www.rti.org). My work and research is focused on compuational chemistry and drug discovery."


# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name : Jerrano L. Bowleg 
  avatar: bio-photo.jpg
  bio: "This is a sample Jekyll academic website."  
  email: "jbowleg@rti.org"
  linkedin: "ttps://www.linkedin.com/in/jerranobowleg"
  github: "https://github.com/chemrano0506"

