title: CompChemRano
locale: en_US
logo: # filename of a logo image that has been placed into your images directory
description: "This research project develops training materials for reseachers wanting to learn to build project
websites in GitHub with GitHub Pages."

name : Jerrano L. Bowleg 
email: "jbowleg@rti.org"
twitter: "https://twitter.com/thecarpentries"
linkedin: "ttps://www.linkedin.com/in/jerranobowleg"
